http:
  listener:
    host: "localhost"
    port: "9091"
    path: "/fastGoCall/{serviceType}"
    
db:
  mysql:
    host: "127.0.0.1"
    port: "3306"
    username: "root"
    password: "root"
    dbname: "newdb"
    